-- MySQL Script generated by MySQL Workbench
-- 10/13/19 10:00:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bcsn2p2qgn5m7jopbpjn
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bcsn2p2qgn5m7jopbpjn
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bcsn2p2qgn5m7jopbpjn` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `bcsn2p2qgn5m7jopbpjn` ;

-- -----------------------------------------------------
-- Table `bcsn2p2qgn5m7jopbpjn`.`TBL_User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bcsn2p2qgn5m7jopbpjn`.`TBL_User` ;

CREATE TABLE IF NOT EXISTS `bcsn2p2qgn5m7jopbpjn`.`TBL_User` (
  `idUser` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(75) NULL COMMENT '',
  `lastname` VARCHAR(75) NULL COMMENT '',
  `email` VARCHAR(75) NULL COMMENT '',
  `phone` VARCHAR(10) NULL COMMENT '',
  `birthday` DATE NULL COMMENT '',
  `username` VARCHAR(75) NULL COMMENT '',
  `password` VARCHAR(225) NULL COMMENT '',
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`idUser`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bcsn2p2qgn5m7jopbpjn`.`TBL_Device`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bcsn2p2qgn5m7jopbpjn`.`TBL_Device` ;

CREATE TABLE IF NOT EXISTS `bcsn2p2qgn5m7jopbpjn`.`TBL_Device` (
  `idDevice` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(255) NULL COMMENT '',
  `permitted` INT(1) NOT NULL DEFAULT 0 COMMENT '',
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  `idUser` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idDevice`)  COMMENT '',
  INDEX `fk_TBL_Device_TBL_User_idx` (`idUser` ASC)  COMMENT '',
  CONSTRAINT `fk_TBL_Device_TBL_User`
    FOREIGN KEY (`idUser`)
    REFERENCES `bcsn2p2qgn5m7jopbpjn`.`TBL_User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bcsn2p2qgn5m7jopbpjn`.`TBL_TypeAuth`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bcsn2p2qgn5m7jopbpjn`.`TBL_TypeAuth` ;

CREATE TABLE IF NOT EXISTS `bcsn2p2qgn5m7jopbpjn`.`TBL_TypeAuth` (
  `idTypeAuth` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `code` VARCHAR(10) NOT NULL COMMENT '',
  `name` VARCHAR(75) NOT NULL COMMENT '',
  `description` VARCHAR(125) NULL COMMENT '',
  `status` INT(1) NOT NULL DEFAULT 0 COMMENT '',
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`idTypeAuth`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bcsn2p2qgn5m7jopbpjn`.`TBL_Token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bcsn2p2qgn5m7jopbpjn`.`TBL_Token` ;

CREATE TABLE IF NOT EXISTS `bcsn2p2qgn5m7jopbpjn`.`TBL_Token` (
  `idToken` INT NOT NULL COMMENT '',
  `token` VARCHAR(5) NOT NULL COMMENT '',
  `expirate` TIMESTAMP NULL COMMENT '',
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  `idUser` INT NOT NULL COMMENT '',
  `idTypeAuth` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idToken`)  COMMENT '',
  INDEX `fk_TBL_Token_TBL_User1_idx` (`idUser` ASC)  COMMENT '',
  INDEX `fk_TBL_Token_TBL_TypeAuth1_idx` (`idTypeAuth` ASC)  COMMENT '',
  CONSTRAINT `fk_TBL_Token_TBL_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `bcsn2p2qgn5m7jopbpjn`.`TBL_User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_Token_TBL_TypeAuth1`
    FOREIGN KEY (`idTypeAuth`)
    REFERENCES `bcsn2p2qgn5m7jopbpjn`.`TBL_TypeAuth` (`idTypeAuth`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bcsn2p2qgn5m7jopbpjn`.`TBL_UserAuthType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bcsn2p2qgn5m7jopbpjn`.`TBL_UserAuthType` ;

CREATE TABLE IF NOT EXISTS `bcsn2p2qgn5m7jopbpjn`.`TBL_UserAuthType` (
  `idUserAuthType` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `status` INT(1) NOT NULL DEFAULT 0 COMMENT '',
  `idUser` INT NOT NULL COMMENT '',
  `idTypeAuth` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idUserAuthType`)  COMMENT '',
  INDEX `fk_TBL_User_has_TBL_TypeAuth_TBL_TypeAuth1_idx` (`idTypeAuth` ASC)  COMMENT '',
  INDEX `fk_TBL_User_has_TBL_TypeAuth_TBL_User1_idx` (`idUser` ASC)  COMMENT '',
  CONSTRAINT `fk_TBL_User_has_TBL_TypeAuth_TBL_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `bcsn2p2qgn5m7jopbpjn`.`TBL_User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_User_has_TBL_TypeAuth_TBL_TypeAuth1`
    FOREIGN KEY (`idTypeAuth`)
    REFERENCES `bcsn2p2qgn5m7jopbpjn`.`TBL_TypeAuth` (`idTypeAuth`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKSsele;




